# Generated by Django 4.0.4 on 2022-04-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cart',
            field=models.ManyToManyField(through='users.Cart', to='products.product'),
        ),
        migrations.AlterField(
            model_name='user',
            name='friend',
            field=models.ManyToManyField(through='users.Friend', to='users.user'),
        ),
    ]
