# Generated by Django 4.0.4 on 2022-04-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_cart_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='cart',
            new_name='carts',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='friend',
            new_name='friends',
        ),
        migrations.AddConstraint(
            model_name='friend',
            constraint=models.UniqueConstraint(fields=('friend_from', 'friend_to'), name='unique_follow'),
        ),
        migrations.AlterModelTable(
            name='cart',
            table='carts',
        ),
    ]
