# Generated by Django 4.0.4 on 2022-04-28 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_review_content_reviewlike_unique_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='rating',
            new_name='score',
        ),
    ]
