# Generated by Django 4.0.4 on 2022-05-03 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_review_content_reviewlike_unique_review'),
        ('reviews', '0004_rename_rating_rating_score_remove_rating_created_at_and_more'),
    ]

    operations = [
    ]
