# Generated by Django 4.0.4 on 2022-04-28 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_alter_orderitemstatus_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitemstatus',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='orderitemstatus',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='ordershipment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='ordershipment',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='orderstatus',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='orderstatus',
            name='updated_at',
        ),
    ]
