# Generated by Django 4.0.4 on 2022-04-27 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='alcohol_percentage',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.AlterModelTable(
            name='foodpairing',
            table='food_pairings',
        ),
        migrations.AlterModelTable(
            name='productfoodpairing',
            table='product_food_pairings',
        ),
    ]
