<<<<<<< HEAD
# Generated by Django 4.0.4 on 2022-04-28 12:29
=======
# Generated by Django 4.0.4 on 2022-04-28 13:17
>>>>>>> 2c505a93012d8d6d897e52425b02eaa7bc7485af

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_alcohol_percentage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='name',
        ),
        migrations.RenameField(
<<<<<<< HEAD
=======
            model_name='country',
            old_name='country',
            new_name='origin',
        ),
        migrations.RenameField(
>>>>>>> 2c505a93012d8d6d897e52425b02eaa7bc7485af
            model_name='product',
            old_name='product_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='average_rating',
        ),
<<<<<<< HEAD
=======
        migrations.RemoveField(
            model_name='product',
            name='content',
        ),
>>>>>>> 2c505a93012d8d6d897e52425b02eaa7bc7485af
    ]
