# Generated by Django 4.0.4 on 2022-04-28 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_category_category_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='country',
            new_name='origin',
        ),
    ]
