# Generated by Django 4.0.4 on 2022-04-28 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_country_country_origin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='content',
        ),
    ]
